// Word Up! word bank
//
// Every clue is hand-written to point at ONE answer. Difficulty comes from how
// much thinking the clue takes, not from obscure vocabulary — every word here
// should be one an average adult in 2026 knows.
//
//   easy   — concrete, everyday things and actions a kid could guess
//   medium — modern life, people, situations; a step of thinking
//   hard   — ideas everyone recognizes but rarely says out loud
//
// Fields: word, pos (part of speech), clue, alt (optional: also-accept answers)
//
// Before committing changes, run:  node scripts/check-words.js
// (checks for duplicates and clues that give away the answer)

window.WORD_BANK = {
  easy: [
    { word: "umbrella", pos: "noun", clue: "You open this over your head to stay dry when it rains." },
    { word: "pillow", pos: "noun", clue: "A soft cushion you rest your head on in bed." },
    { word: "ladder", pos: "noun", clue: "A tall frame with steps that you climb to reach high places." },
    { word: "sneeze", pos: "verb", clue: "To suddenly blast air out of your nose — achoo!" },
    { word: "yawn", pos: "verb", clue: "To open your mouth wide and take a deep breath because you're tired or bored." },
    { word: "hiccup", pos: "noun", clue: "A sudden little jump in your chest that makes a 'hic' sound over and over.", alt: ["hiccups"] },
    { word: "toothbrush", pos: "noun", clue: "A small tool with bristles you use twice a day to clean your teeth." },
    { word: "mirror", pos: "noun", clue: "A shiny glass surface that shows your reflection." },
    { word: "wallet", pos: "noun", clue: "A small folding case for carrying cash and cards in your pocket.", alt: ["purse"] },
    { word: "blanket", pos: "noun", clue: "A big warm cover you pull over yourself in bed or on the couch." },
    { word: "candle", pos: "noun", clue: "A stick of wax with a wick that you light for a small flame." },
    { word: "kite", pos: "noun", clue: "A paper or fabric toy on a long string that you fly in the wind." },
    { word: "sandwich", pos: "noun", clue: "Two slices of bread with something like ham or cheese in between." },
    { word: "pancake", pos: "noun", clue: "A flat, round breakfast food cooked on a griddle and topped with syrup.", alt: ["flapjack", "hotcake"] },
    { word: "popcorn", pos: "noun", clue: "Kernels that puff up when heated — the classic movie theater snack." },
    { word: "icicle", pos: "noun", clue: "A pointy frozen spike hanging from a roof in winter." },
    { word: "rainbow", pos: "noun", clue: "An arc of colors in the sky when the sun comes out after a storm." },
    { word: "thunder", pos: "noun", clue: "The loud, rumbling boom you hear after lightning." },
    { word: "puddle", pos: "noun", clue: "A small pool of water on the ground after it rains." },
    { word: "shadow", pos: "noun", clue: "The dark shape your body makes on the ground when you block the light." },
    { word: "balloon", pos: "noun", clue: "A rubber bag you fill with air or helium for a party." },
    { word: "scissors", pos: "noun", clue: "A tool with two blades that you use to cut paper." },
    { word: "envelope", pos: "noun", clue: "A paper pocket you put a letter in before mailing it." },
    { word: "calendar", pos: "noun", clue: "A chart of days, weeks, and months that you use to plan ahead." },
    { word: "doorbell", pos: "noun", clue: "The button outside a house that rings when visitors arrive." },
    { word: "fridge", pos: "noun", clue: "The cold kitchen appliance that keeps food and drinks chilled.", alt: ["refrigerator"] },
    { word: "microwave", pos: "noun", clue: "The kitchen appliance that heats up leftovers in a couple of minutes." },
    { word: "vacuum", pos: "noun", clue: "A noisy machine that sucks dust and crumbs off the floor." },
    { word: "laundry", pos: "noun", clue: "Dirty clothes waiting to be washed — or the chore of washing them." },
    { word: "backpack", pos: "noun", clue: "A bag with two straps that you wear on your shoulders.", alt: ["bookbag", "rucksack"] },
    { word: "sunglasses", pos: "noun", clue: "Dark lenses you wear to protect your eyes on a bright day.", alt: ["shades"] },
    { word: "sock", pos: "noun", clue: "A soft piece of clothing you pull over your foot before your shoe.", alt: ["socks"] },
    { word: "zipper", pos: "noun", clue: "Two rows of tiny teeth that lock together to close a jacket or bag.", alt: ["zip"] },
    { word: "helmet", pos: "noun", clue: "A hard hat you wear to protect your head when riding a bike." },
    { word: "bicycle", pos: "noun", clue: "Two wheels, pedals, and handlebars — you ride it without a motor.", alt: ["bike"] },
    { word: "skateboard", pos: "noun", clue: "A flat deck on four small wheels that you ride and do kickflips on." },
    { word: "elevator", pos: "noun", clue: "A box that carries people up and down between floors of a building.", alt: ["lift"] },
    { word: "stairs", pos: "noun", clue: "What you climb to get from one floor to the next when there's no elevator.", alt: ["staircase", "steps"] },
    { word: "bridge", pos: "noun", clue: "A structure that lets you cross over a river or road." },
    { word: "tunnel", pos: "noun", clue: "An underground passage that cars or trains drive through." },
    { word: "airport", pos: "noun", clue: "The place where you check bags, go through security, and board a plane." },
    { word: "passport", pos: "noun", clue: "The small booklet you need to show to travel to another country." },
    { word: "suitcase", pos: "noun", clue: "A rolling bag you pack your clothes in for a trip.", alt: ["luggage"] },
    { word: "compass", pos: "noun", clue: "A tool with a needle that always points north." },
    { word: "volcano", pos: "noun", clue: "A mountain that can erupt and pour out lava." },
    { word: "desert", pos: "noun", clue: "A hot, dry, sandy place where it hardly ever rains." },
    { word: "island", pos: "noun", clue: "A piece of ground with water all the way around it, like Hawaii." },
    { word: "beach", pos: "noun", clue: "The sandy place next to the ocean where people swim and sunbathe.", alt: ["shore"] },
    { word: "penguin", pos: "noun", clue: "A black-and-white bird that can't fly but swims really well." },
    { word: "giraffe", pos: "noun", clue: "The tallest animal on Earth, with a super long neck." },
    { word: "kangaroo", pos: "noun", clue: "An Australian animal that hops and carries its baby in a pouch." },
    { word: "octopus", pos: "noun", clue: "A sea creature with eight arms that can squirt ink." },
    { word: "squirrel", pos: "noun", clue: "A bushy-tailed animal that climbs trees and stores nuts." },
    { word: "spider", pos: "noun", clue: "An eight-legged creature that spins a web." },
    { word: "snail", pos: "noun", clue: "A slow, slimy creature that carries its shell on its back." },
    { word: "owl", pos: "noun", clue: "A bird that's awake at night and says 'hoo, hoo.'" },
    { word: "bee", pos: "noun", clue: "A buzzing insect that makes honey and can sting.", alt: ["honeybee", "bumblebee"] },
    { word: "butterfly", pos: "noun", clue: "An insect with colorful wings that starts life as a caterpillar." },
    { word: "dinosaur", pos: "noun", clue: "A giant reptile that lived millions of years ago, like T. rex." },
    { word: "shark", pos: "noun", clue: "A big ocean fish with rows of sharp teeth and a fin that sticks out of the water." },
    { word: "parrot", pos: "noun", clue: "A colorful bird that can copy human words." },
    { word: "unicorn", pos: "noun", clue: "A magical horse with a single horn on its forehead." },
    { word: "dragon", pos: "noun", clue: "A fire-breathing monster with wings and scales." },
    { word: "zombie", pos: "noun", clue: "A dead body that gets up and shuffles around hungry for brains.", alt: ["undead", "walker"] },
    { word: "pirate", pos: "noun", clue: "A sailor who robs ships and hunts for buried treasure." },
    { word: "wizard", pos: "noun", clue: "A person in a robe and pointy hat who casts spells.", alt: ["sorcerer", "magician", "witch"] },
    { word: "robot", pos: "noun", clue: "A machine that can move and do tasks on its own." },
    { word: "astronaut", pos: "noun", clue: "A person who travels into space.", alt: ["cosmonaut"] },
    { word: "firefighter", pos: "noun", clue: "A person who puts out blazes and rides a big red truck.", alt: ["fireman"] },
    { word: "dentist", pos: "noun", clue: "The doctor who checks and cleans your teeth." },
    { word: "chef", pos: "noun", clue: "The person who cooks the food in a restaurant kitchen.", alt: ["cook"] },
    { word: "farmer", pos: "noun", clue: "A person who grows crops and raises animals." },
    { word: "lifeguard", pos: "noun", clue: "The person who watches swimmers at a pool or beach to keep them safe." },
    { word: "pizza", pos: "noun", clue: "A round flatbread with tomato sauce, cheese, and toppings, cut into slices." },
    { word: "cereal", pos: "noun", clue: "A breakfast food you pour into a bowl and eat with milk." },
    { word: "cookie", pos: "noun", clue: "A small, sweet baked treat — chocolate chip is a classic.", alt: ["biscuit"] },
    { word: "cupcake", pos: "noun", clue: "A small frosted treat baked in a paper liner.", alt: ["muffin"] },
    { word: "spaghetti", pos: "noun", clue: "Long, thin noodles often served with meatballs.", alt: ["pasta"] },
    { word: "taco", pos: "noun", clue: "A folded tortilla stuffed with meat, cheese, and salsa." },
    { word: "lemonade", pos: "noun", clue: "The sweet-and-sour yellow drink kids sell at stands in summer." },
    { word: "banana", pos: "noun", clue: "A long yellow fruit you peel — monkeys love it." },
    { word: "watermelon", pos: "noun", clue: "A big green-striped fruit that's red, juicy, and full of seeds inside." },
    { word: "pineapple", pos: "noun", clue: "A spiky tropical fruit with a crown of leaves on top." },
    { word: "coffee", pos: "noun", clue: "A hot, dark drink made from roasted beans that wakes you up." },
    { word: "ketchup", pos: "noun", clue: "The red tomato sauce you squeeze onto fries.", alt: ["catsup"] },
    { word: "pajamas", pos: "noun", clue: "Comfy clothes you wear to sleep.", alt: ["pyjamas", "pjs"] },
    { word: "nap", pos: "noun", clue: "A short sleep during the day.", alt: ["snooze"] },
    { word: "snore", pos: "verb", clue: "To make loud breathing noises while you're asleep." },
    { word: "whisper", pos: "verb", clue: "To speak very quietly so only someone close by can hear." },
    { word: "giggle", pos: "verb", clue: "To let out a quiet, silly little laugh.", alt: ["chuckle", "snicker"] },
    { word: "blink", pos: "verb", clue: "To quickly shut and open both eyes." },
    { word: "wink", pos: "verb", clue: "To close one eye on purpose, often as a joke or secret signal." },
    { word: "hug", pos: "verb", clue: "To wrap your arms around someone to show you care.", alt: ["embrace", "cuddle"] },
    { word: "clap", pos: "verb", clue: "To smack your hands together, like at the end of a show.", alt: ["applaud"] },
    { word: "juggle", pos: "verb", clue: "To keep tossing several balls into the air without dropping any." },
    { word: "sweat", pos: "noun", clue: "Salty water your skin makes when you're hot or exercising.", alt: ["perspiration"] },
    { word: "tickle", pos: "verb", clue: "To lightly poke someone's sides so they laugh and squirm." },
    { word: "shiver", pos: "verb", clue: "To shake all over because you're cold.", alt: ["shudder", "tremble"] },
    { word: "bake", pos: "verb", clue: "To cook something like bread or cake in an oven." },
    { word: "recycle", pos: "verb", clue: "To put used bottles and paper in a special bin so they can be made into new things." },
    { word: "homework", pos: "noun", clue: "Assignments a teacher gives you to finish after school." },
    { word: "birthday", pos: "noun", clue: "The yearly day you celebrate being born, with cake and candles." },
    { word: "vacation", pos: "noun", clue: "Time off from work or school to travel or relax.", alt: ["holiday"] },
    { word: "picnic", pos: "noun", clue: "A meal you eat outdoors on a blanket in the park." },
    { word: "camping", pos: "noun", clue: "Sleeping outside in a tent for fun." },
    { word: "fireworks", pos: "noun", clue: "Colorful explosions in the night sky on the Fourth of July or New Year's.", alt: ["firework"] },
    { word: "snowman", pos: "noun", clue: "A winter figure with a carrot nose, coal eyes, and stick arms." },
    { word: "sled", pos: "noun", clue: "The thing you ride down a snowy hill.", alt: ["sledge", "sleigh", "toboggan"] },
    { word: "haircut", pos: "noun", clue: "What you get at the barber or salon when things are getting too long.", alt: ["trim"] },
    { word: "selfie", pos: "noun", clue: "A photo you take of yourself with your phone." },
    { word: "emoji", pos: "noun", clue: "A little picture, like a smiley face, that you add to a text." },
    { word: "remote", pos: "noun", clue: "The gadget you use to change the TV channel from the couch.", alt: ["clicker"] },
    { word: "headphones", pos: "noun", clue: "You wear these over your ears to listen to music without bothering anyone.", alt: ["earbuds", "headset"] },
    { word: "charger", pos: "noun", clue: "The cord you plug in when your phone battery is low." },
    { word: "keyboard", pos: "noun", clue: "The rows of letter buttons you type on." },
    { word: "battery", pos: "noun", clue: "The thing that powers toys and remotes — and always runs out at the worst time." },
    { word: "trampoline", pos: "noun", clue: "A bouncy mat on springs that you jump on in the backyard." },
    { word: "swing", pos: "noun", clue: "A playground seat hanging from chains that you pump back and forth." },
    { word: "puzzle", pos: "noun", clue: "A game where you fit pieces together to make a picture.", alt: ["jigsaw"] },
    { word: "dice", pos: "noun", clue: "Small cubes with one to six dots that you roll in board games.", alt: ["die"] },
    { word: "crayon", pos: "noun", clue: "A colored wax stick kids use to draw." },
    { word: "magnet", pos: "noun", clue: "An object that pulls paperclips and other metal things toward it." },
    { word: "telescope", pos: "noun", clue: "A long tube you look through to see faraway stars and planets." },
    { word: "thermometer", pos: "noun", clue: "A tool that measures how hot or cold something is — like checking for a fever." },
    { word: "bandage", pos: "noun", clue: "A strip you stick over a cut to cover it.", alt: ["band-aid", "plaster"] },
    { word: "crown", pos: "noun", clue: "The gold headpiece a king or queen wears.", alt: ["tiara"] },
    { word: "castle", pos: "noun", clue: "A big stone building with towers where kings and queens lived.", alt: ["palace", "fortress"] },
    { word: "treasure", pos: "noun", clue: "Gold and jewels that pirates bury and hunt for." },
    { word: "hammock", pos: "noun", clue: "A hanging bed of cloth or net strung between two trees." },
    { word: "stapler", pos: "noun", clue: "The desk tool that clips papers together with a little metal piece." },
    { word: "tissue", pos: "noun", clue: "The soft paper you blow your nose into.", alt: ["kleenex"] },
    { word: "toaster", pos: "noun", clue: "The kitchen gadget that browns bread slices and pops them up." },
    { word: "trash", pos: "noun", clue: "Stuff you throw away.", alt: ["garbage", "rubbish", "junk"] },
    { word: "drum", pos: "noun", clue: "An instrument you hit with sticks to keep the beat.", alt: ["drums"] },
    { word: "guitar", pos: "noun", clue: "An instrument with six strings that you strum." },
    { word: "piano", pos: "noun", clue: "A big instrument with black and white keys." },
    { word: "cartoon", pos: "noun", clue: "An animated show, often made for kids." },
    { word: "mustache", pos: "noun", clue: "Hair that grows just above someone's upper lip.", alt: ["moustache"] },
    { word: "freckles", pos: "noun", clue: "Little brown spots on your skin, often from the sun.", alt: ["freckle"] },
    { word: "elbow", pos: "noun", clue: "The joint in the middle of your arm that lets it bend." },
    { word: "knee", pos: "noun", clue: "The joint in the middle of your leg." },
    { word: "thumb", pos: "noun", clue: "The short, thick finger you give a 'like' with." },
    { word: "tongue", pos: "noun", clue: "The pink muscle in your mouth that you taste with." },
    { word: "skeleton", pos: "noun", clue: "All the bones of a body put together — a Halloween favorite." },
    { word: "mummy", pos: "noun", clue: "An ancient Egyptian body wrapped head to toe in cloth." },
    { word: "igloo", pos: "noun", clue: "A dome-shaped house made from blocks of snow." },
    { word: "tent", pos: "noun", clue: "A fabric shelter you set up with poles when you go camping." },
    { word: "lighthouse", pos: "noun", clue: "A tall tower on the coast with a bright beam to warn ships." },
    { word: "fountain", pos: "noun", clue: "A structure that shoots water into the air — people toss coins in it." },
    { word: "mailbox", pos: "noun", clue: "The box at the end of the driveway where letters get delivered.", alt: ["postbox", "letterbox"] },
    { word: "carrot", pos: "noun", clue: "A long orange vegetable rabbits love to munch." },
    { word: "broccoli", pos: "noun", clue: "A green vegetable that looks like a tiny tree." },
    { word: "pumpkin", pos: "noun", clue: "A big orange squash you carve a face into for Halloween.", alt: ["jack-o'-lantern"] },
    { word: "marshmallow", pos: "noun", clue: "A fluffy white treat you roast on a stick over a campfire." },
    { word: "sprinkles", pos: "noun", clue: "Tiny colorful bits scattered on top of ice cream or donuts.", alt: ["jimmies"] },
    { word: "scarecrow", pos: "noun", clue: "A straw-stuffed figure in a field that keeps birds away." },
    { word: "wheelchair", pos: "noun", clue: "A seat on wheels for people who can't walk." }
  ],

  medium: [
    { word: "nostalgia", pos: "noun", clue: "A warm, wistful longing for the good old days." },
    { word: "procrastinate", pos: "verb", clue: "To keep putting off something you need to do until the last minute.", alt: ["stall", "dawdle"] },
    { word: "deadline", pos: "noun", clue: "The date or time something absolutely has to be finished by.", alt: ["due date"] },
    { word: "spoiler", pos: "noun", clue: "Info that gives away the ending of a movie or show before you've seen it." },
    { word: "binge", pos: "verb", clue: "To watch an entire season of a show in one sitting.", alt: ["binge-watch"] },
    { word: "podcast", pos: "noun", clue: "A talk show you stream and listen to on your commute." },
    { word: "screenshot", pos: "noun", clue: "A picture of exactly what's on your phone or computer display, often used as receipts.", alt: ["screengrab"] },
    { word: "influencer", pos: "noun", clue: "A person with a huge social media following who gets paid to promote products." },
    { word: "hashtag", pos: "noun", clue: "A word or phrase with a # in front of it, used to tag posts." },
    { word: "meme", pos: "noun", clue: "A funny image or video that spreads fast across the internet, often with a caption." },
    { word: "ghosting", pos: "noun", clue: "Suddenly cutting off all contact with someone you were dating, with no explanation.", alt: ["ghost"] },
    { word: "wifi", pos: "noun", clue: "The wireless connection you always ask for the password to at a friend's house.", alt: ["wi-fi", "internet"] },
    { word: "autocorrect", pos: "noun", clue: "The phone feature that 'fixes' your typing — sometimes into something embarrassing." },
    { word: "karaoke", pos: "noun", clue: "Singing along to lyrics on a screen, usually badly, at a bar or party." },
    { word: "souvenir", pos: "noun", clue: "A small item you buy on a trip to remember it by.", alt: ["keepsake", "memento"] },
    { word: "hangover", pos: "noun", clue: "The headache and queasy feeling the morning after drinking too much." },
    { word: "brunch", pos: "noun", clue: "A late-morning meal that's half breakfast, half lunch." },
    { word: "leftovers", pos: "noun", clue: "Food from last night's dinner that you eat again the next day." },
    { word: "takeout", pos: "noun", clue: "Restaurant food you pick up and eat at home.", alt: ["takeaway", "carryout"] },
    { word: "tip", pos: "noun", clue: "Extra money you leave your server for good service.", alt: ["gratuity"] },
    { word: "receipt", pos: "noun", clue: "The slip of paper that proves what you bought and how much you paid." },
    { word: "budget", pos: "noun", clue: "A plan for how much money you'll spend and how much you'll save." },
    { word: "mortgage", pos: "noun", clue: "The big loan most people take out to buy a house." },
    { word: "landlord", pos: "noun", clue: "The person who owns the apartment you rent and collects your payment each month.", alt: ["landlady"] },
    { word: "roommate", pos: "noun", clue: "The person you share an apartment with.", alt: ["flatmate", "housemate"] },
    { word: "commute", pos: "noun", clue: "Your daily trip to and from work." },
    { word: "gridlock", pos: "noun", clue: "When cars are packed so tightly on the roads that nobody can move.", alt: ["traffic", "traffic jam"] },
    { word: "detour", pos: "noun", clue: "A different, longer route you take because the usual road is blocked." },
    { word: "shortcut", pos: "noun", clue: "A quicker way to get somewhere — or to get something done." },
    { word: "allergy", pos: "noun", clue: "When your body reacts badly to things like pollen, peanuts, or cats." },
    { word: "vaccine", pos: "noun", clue: "A shot that trains your body to fight off a disease.", alt: ["vaccination", "immunization"] },
    { word: "insomnia", pos: "noun", clue: "Trouble falling or staying asleep, night after night." },
    { word: "nightmare", pos: "noun", clue: "A scary dream that wakes you up in a cold sweat." },
    { word: "goosebumps", pos: "noun", clue: "Tiny raised dots on your arms when you're cold, scared, or moved by a song.", alt: ["goose bumps", "chills"] },
    { word: "awkward", pos: "adjective", clue: "Uncomfortable and clumsy — like an unexpected silence on a first date." },
    { word: "sarcastic", pos: "adjective", clue: "Saying the opposite of what you mean to mock something, like 'Oh, great' when it all goes wrong." },
    { word: "jealous", pos: "adjective", clue: "Upset because someone else has something you want.", alt: ["envious"] },
    { word: "gossip", pos: "noun", clue: "Juicy talk about other people's private lives behind their backs." },
    { word: "rumor", pos: "noun", clue: "A story going around that may or may not be true.", alt: ["rumour", "hearsay"] },
    { word: "crush", pos: "noun", clue: "A secret romantic feeling for someone." },
    { word: "breakup", pos: "noun", clue: "The end of a romantic relationship.", alt: ["split"] },
    { word: "wedding", pos: "noun", clue: "The ceremony where two people get married.", alt: ["marriage"] },
    { word: "honeymoon", pos: "noun", clue: "The trip newlyweds take right after the ceremony." },
    { word: "anniversary", pos: "noun", clue: "The yearly celebration of the date something important happened, like a marriage." },
    { word: "retirement", pos: "noun", clue: "When you stop working for good, usually later in life." },
    { word: "promotion", pos: "noun", clue: "Moving up to a better job title at work, usually with a raise." },
    { word: "interview", pos: "noun", clue: "A meeting where someone asks you questions to decide if you get the job." },
    { word: "resume", pos: "noun", clue: "A one-page summary of your work experience that you send when applying for jobs.", alt: ["cv", "résumé"] },
    { word: "coworker", pos: "noun", clue: "Someone at your job you see every day — maybe at the coffee machine.", alt: ["colleague"] },
    { word: "refund", pos: "noun", clue: "Getting your money back when you return something." },
    { word: "warranty", pos: "noun", clue: "A promise to fix or replace a product if it breaks within a set time.", alt: ["guarantee"] },
    { word: "subscription", pos: "noun", clue: "Paying every month to keep getting a service like streaming — easy to forget you have." },
    { word: "algorithm", pos: "noun", clue: "The behind-the-scenes rules an app uses to decide what shows up in your feed." },
    { word: "notification", pos: "noun", clue: "The ping that pops up on your lock screen when something new happens.", alt: ["alert"] },
    { word: "bookmark", pos: "noun", clue: "A strip of paper that saves your page in a novel — or a saved link in your browser." },
    { word: "typo", pos: "noun", clue: "A small mistake you make while typing." },
    { word: "voicemail", pos: "noun", clue: "The recorded message someone leaves when you don't pick up the phone." },
    { word: "avatar", pos: "noun", clue: "The picture or character that represents you online or in a video game.", alt: ["profile picture"] },
    { word: "trophy", pos: "noun", clue: "The gold cup or statue you get for winning a competition." },
    { word: "referee", pos: "noun", clue: "The person in stripes who enforces the rules and blows the whistle during a game.", alt: ["ref", "umpire", "official"] },
    { word: "overtime", pos: "noun", clue: "Extra time played when a game ends tied — or extra hours at work." },
    { word: "marathon", pos: "noun", clue: "A 26.2-mile running race." },
    { word: "tournament", pos: "noun", clue: "A competition where many teams play in rounds until one is left standing." },
    { word: "underdog", pos: "noun", clue: "The team or person everyone expects to lose." },
    { word: "rematch", pos: "noun", clue: "A second game between the same opponents, usually because the loser demands it." },
    { word: "dare", pos: "noun", clue: "A challenge to do something risky or embarrassing — 'truth or ___?'" },
    { word: "riddle", pos: "noun", clue: "A tricky question with a clever answer, like 'What has keys but can't open locks?'" },
    { word: "magician", pos: "noun", clue: "A performer who pulls rabbits out of hats and saws people in half.", alt: ["illusionist"] },
    { word: "audience", pos: "noun", clue: "The group of people watching a show.", alt: ["crowd"] },
    { word: "encore", pos: "noun", clue: "The extra song a band plays because the crowd keeps cheering for more." },
    { word: "sequel", pos: "noun", clue: "A movie or book that continues the story of an earlier one.", alt: ["part two"] },
    { word: "trailer", pos: "noun", clue: "The two-minute sneak peek of an upcoming movie.", alt: ["teaser", "preview"] },
    { word: "cliffhanger", pos: "noun", clue: "An episode ending that leaves you in suspense until the next one." },
    { word: "villain", pos: "noun", clue: "The bad guy in a story.", alt: ["antagonist"] },
    { word: "sidekick", pos: "noun", clue: "The hero's loyal helper, like Robin to Batman." },
    { word: "superhero", pos: "noun", clue: "A character with special powers who saves the day, like Spider-Man." },
    { word: "detective", pos: "noun", clue: "A person who investigates crimes and solves mysteries, like Sherlock Holmes." },
    { word: "alibi", pos: "noun", clue: "Proof that you were somewhere else when the crime happened." },
    { word: "witness", pos: "noun", clue: "A person who saw something happen and can describe it in court.", alt: ["eyewitness"] },
    { word: "jury", pos: "noun", clue: "The group of ordinary citizens who decide guilty or not guilty in court." },
    { word: "ransom", pos: "noun", clue: "Money demanded to free someone who's been kidnapped." },
    { word: "tsunami", pos: "noun", clue: "A giant ocean wave caused by an underwater earthquake.", alt: ["tidal wave"] },
    { word: "tornado", pos: "noun", clue: "A spinning funnel of wind that touches down and tears things apart.", alt: ["twister", "cyclone"] },
    { word: "drought", pos: "noun", clue: "A long stretch of time with little or no rain." },
    { word: "avalanche", pos: "noun", clue: "A huge mass of snow crashing down a mountainside." },
    { word: "eclipse", pos: "noun", clue: "When the moon passes in front of the sun and blocks it out." },
    { word: "horizon", pos: "noun", clue: "The line in the distance where the sky seems to meet the land or sea." },
    { word: "fossil", pos: "noun", clue: "The remains of an ancient plant or animal preserved in rock." },
    { word: "vegetarian", pos: "noun", clue: "Someone who doesn't eat meat.", alt: ["vegan"] },
    { word: "recipe", pos: "noun", clue: "Instructions for cooking a dish, with ingredients and steps." },
    { word: "appetizer", pos: "noun", clue: "A small dish served before the main course.", alt: ["starter"] },
    { word: "dessert", pos: "noun", clue: "The sweet course at the end of a meal." },
    { word: "buffet", pos: "noun", clue: "An all-you-can-eat spread where you serve yourself." },
    { word: "caffeine", pos: "noun", clue: "The stimulant in coffee and energy drinks that keeps you awake." },
    { word: "picky", pos: "adjective", clue: "Hard to please — especially about what's on your plate.", alt: ["fussy", "choosy"] },
    { word: "clumsy", pos: "adjective", clue: "Always tripping, dropping things, or bumping into furniture." },
    { word: "gullible", pos: "adjective", clue: "So easily fooled that you'll believe almost anything.", alt: ["naive"] },
    { word: "stubborn", pos: "adjective", clue: "Refusing to change your mind no matter what anyone says.", alt: ["obstinate", "pigheaded"] },
    { word: "generous", pos: "adjective", clue: "Happy to share and give more than people expect." },
    { word: "grumpy", pos: "adjective", clue: "Bad-tempered and complaining, especially before coffee.", alt: ["cranky", "grouchy"] },
    { word: "embarrassed", pos: "adjective", clue: "Red-faced and self-conscious after doing something awkward in public.", alt: ["mortified", "ashamed"] },
    { word: "homesick", pos: "adjective", clue: "Missing your family and your own house while you're away at camp or college." },
    { word: "exhausted", pos: "adjective", clue: "Completely worn out with no energy left.", alt: ["tired", "drained", "wiped out"] },
    { word: "optimist", pos: "noun", clue: "Someone who always sees the glass as half full." },
    { word: "pessimist", pos: "noun", clue: "Someone who always expects the worst to happen." },
    { word: "perfectionist", pos: "noun", clue: "Someone who can't rest until every last detail is flawless." },
    { word: "introvert", pos: "noun", clue: "Someone who recharges by spending time alone." },
    { word: "extrovert", pos: "noun", clue: "Someone who gets energy from being around lots of people." },
    { word: "brag", pos: "verb", clue: "To talk proudly about how great you are.", alt: ["boast", "show off"] },
    { word: "apologize", pos: "verb", clue: "To tell someone you're sorry.", alt: ["apologise"] },
    { word: "negotiate", pos: "verb", clue: "To go back and forth bargaining until both sides agree on a deal.", alt: ["haggle", "bargain"] },
    { word: "volunteer", pos: "verb", clue: "To offer to help without getting paid." },
    { word: "multitask", pos: "verb", clue: "To juggle several jobs at the same time." },
    { word: "eavesdrop", pos: "verb", clue: "To secretly listen in on someone else's conversation." },
    { word: "snooze", pos: "verb", clue: "To hit the button on your alarm for ten more minutes of sleep." },
    { word: "overthink", pos: "verb", clue: "To keep replaying and analyzing something way more than you need to.", alt: ["overanalyze"] },
    { word: "hibernate", pos: "verb", clue: "What bears do when they sleep through the whole winter." },
    { word: "migrate", pos: "verb", clue: "What birds do when they fly south for the winter." },
    { word: "camouflage", pos: "noun", clue: "Colors or patterns that help something blend into its surroundings." },
    { word: "compost", pos: "noun", clue: "Rotting food scraps and leaves that turn into rich garden soil." },
    { word: "graffiti", pos: "noun", clue: "Writing or drawings spray-painted on walls." },
    { word: "tattoo", pos: "noun", clue: "A permanent design drawn into your skin with a needle.", alt: ["ink"] },
    { word: "secondhand", pos: "adjective", clue: "Already owned by someone else before you, like thrift-store clothes.", alt: ["used", "pre-owned", "thrifted"] },
    { word: "bargain", pos: "noun", clue: "Something you bought for way less than it's worth.", alt: ["deal", "steal"] },
    { word: "layover", pos: "noun", clue: "A stop between flights while you wait for your connecting plane.", alt: ["stopover"] },
    { word: "turbulence", pos: "noun", clue: "Bumpy air that shakes the plane mid-flight." },
    { word: "hostel", pos: "noun", clue: "Cheap shared lodging with bunk beds, popular with backpackers." },
    { word: "viral", pos: "adjective", clue: "Spreading incredibly fast across the internet." },
    { word: "cringe", pos: "adjective", clue: "So awkward or embarrassing it makes you wince.", alt: ["cringey", "cringy"] },
    { word: "unboxing", pos: "noun", clue: "A video of someone opening a new product for the first time." },
    { word: "playlist", pos: "noun", clue: "The set of songs you put together for a road trip or workout.", alt: ["mix", "mixtape"] },
    { word: "streaming", pos: "noun", clue: "Watching or listening online without downloading, like on Netflix or Spotify." },
    { word: "livestream", pos: "noun", clue: "A video broadcast in real time on the internet.", alt: ["live stream"] },
    { word: "bouncer", pos: "noun", clue: "The big person at the club door who checks IDs and keeps out troublemakers." },
    { word: "babysitter", pos: "noun", clue: "Someone you pay to watch your kids while you go out.", alt: ["nanny", "sitter"] },
    { word: "lullaby", pos: "noun", clue: "A soft song you sing to help a baby fall asleep." },
    { word: "tantrum", pos: "noun", clue: "A screaming, kicking fit a toddler throws when they don't get their way.", alt: ["meltdown"] },
    { word: "carpool", pos: "noun", clue: "When several people share one car to get to work or school.", alt: ["rideshare"] },
    { word: "potluck", pos: "noun", clue: "A party where every guest brings a dish to share." },
    { word: "sleepover", pos: "noun", clue: "When kids spend the night at a friend's house.", alt: ["slumber party"] },
    { word: "scavenger", pos: "noun", clue: "An animal like a vulture that eats what other animals leave behind." },
    { word: "landslide", pos: "noun", clue: "An election won by a huge margin — or a mountainside of mud sliding down." },
    { word: "mascot", pos: "noun", clue: "The costumed character that cheers on a sports team." },
    { word: "tailgate", pos: "verb", clue: "To drive dangerously close behind another car — or party in a stadium parking lot." },
    { word: "jaywalk", pos: "verb", clue: "To cross the street illegally, away from the crosswalk." },
    { word: "freelance", pos: "adjective", clue: "Working for yourself and taking jobs from different clients instead of one employer.", alt: ["self-employed", "freelancer"] },
    { word: "paycheck", pos: "noun", clue: "The money your employer pays you every couple of weeks.", alt: ["salary", "wages", "pay"] },
    { word: "overdraft", pos: "noun", clue: "When you spend more than you have in your bank account and get hit with a fee." },
    { word: "jackpot", pos: "noun", clue: "The biggest prize in a lottery or slot machine." },
    { word: "lottery", pos: "noun", clue: "A game where you buy a ticket and hope your numbers get drawn.", alt: ["lotto"] },
    { word: "horoscope", pos: "noun", clue: "A prediction about your week based on your star sign." },
    { word: "zodiac", pos: "noun", clue: "The twelve star signs, like Leo, Virgo, and Scorpio." }
  ],

  hard: [
    { word: "irony", pos: "noun", clue: "When the outcome is the opposite of what you'd expect — like a fire station burning down." },
    { word: "paradox", pos: "noun", clue: "A statement that seems to contradict itself but might still be true, like 'less is more.'" },
    { word: "hypocrite", pos: "noun", clue: "Someone who criticizes others for doing the exact thing they do themselves." },
    { word: "euphemism", pos: "noun", clue: "A gentle way of saying something harsh, like 'passed away' instead of 'died.'" },
    { word: "cliche", pos: "noun", clue: "A phrase used so much it's lost its punch, like 'at the end of the day.'", alt: ["cliché"] },
    { word: "placebo", pos: "noun", clue: "A fake pill that works only because the patient believes it will." },
    { word: "nepotism", pos: "noun", clue: "Handing out jobs to your relatives instead of the most qualified person." },
    { word: "loophole", pos: "noun", clue: "A gap in the rules that lets you get around them legally." },
    { word: "stalemate", pos: "noun", clue: "A situation where neither side can win or make a move.", alt: ["deadlock", "standoff", "impasse"] },
    { word: "sabotage", pos: "verb", clue: "To secretly wreck someone's plans or work from the inside." },
    { word: "gaslight", pos: "verb", clue: "To manipulate someone until they doubt their own memory and sanity.", alt: ["gaslighting"] },
    { word: "propaganda", pos: "noun", clue: "One-sided information spread on purpose to push a political cause." },
    { word: "censorship", pos: "noun", clue: "Blocking or deleting speech, books, or media that authorities don't like." },
    { word: "bureaucracy", pos: "noun", clue: "Endless paperwork, rules, and red tape in a big organization or government." },
    { word: "monopoly", pos: "noun", clue: "When one company controls an entire market with no competition." },
    { word: "inflation", pos: "noun", clue: "When prices keep rising and the same money buys you less." },
    { word: "recession", pos: "noun", clue: "A period when the economy shrinks and lots of people lose their jobs.", alt: ["depression", "downturn"] },
    { word: "philanthropist", pos: "noun", clue: "A wealthy person who gives away large sums to charity." },
    { word: "entrepreneur", pos: "noun", clue: "Someone who starts their own business and takes on the risk." },
    { word: "ambiguous", pos: "adjective", clue: "Unclear because it could be understood in more than one way.", alt: ["vague"] },
    { word: "empathy", pos: "noun", clue: "The ability to put yourself in someone else's shoes and feel what they feel.", alt: ["compassion", "sympathy"] },
    { word: "resilient", pos: "adjective", clue: "Able to bounce back quickly after tough times." },
    { word: "meticulous", pos: "adjective", clue: "Extremely careful about every tiny detail.", alt: ["thorough", "precise"] },
    { word: "skeptical", pos: "adjective", clue: "Not easily convinced — 'I'll believe it when I see it.'", alt: ["sceptical", "doubtful"] },
    { word: "nonchalant", pos: "adjective", clue: "Calm and casual, acting like you couldn't care less.", alt: ["indifferent", "laid-back"] },
    { word: "pretentious", pos: "adjective", clue: "Trying to seem more cultured or important than you really are.", alt: ["snobby", "snobbish"] },
    { word: "condescending", pos: "adjective", clue: "Talking down to people as if they're not as smart as you.", alt: ["patronizing", "patronising"] },
    { word: "narcissist", pos: "noun", clue: "Someone obsessed with themselves who constantly craves admiration." },
    { word: "hypochondriac", pos: "noun", clue: "Someone convinced every sniffle or ache means a serious illness." },
    { word: "claustrophobic", pos: "adjective", clue: "Panicky in small, tight, enclosed spaces like elevators." },
    { word: "epiphany", pos: "noun", clue: "A sudden 'aha!' moment when something finally makes sense.", alt: ["revelation", "realization"] },
    { word: "serendipity", pos: "noun", clue: "A happy accident — finding something wonderful without looking for it." },
    { word: "coincidence", pos: "noun", clue: "When two things happen at the same time by pure chance, as if it were planned." },
    { word: "karma", pos: "noun", clue: "The idea that what goes around comes around." },
    { word: "jinx", pos: "verb", clue: "To bring bad luck on something by talking about it too soon." },
    { word: "superstition", pos: "noun", clue: "A belief that something like a black cat or a broken mirror brings bad luck." },
    { word: "omen", pos: "noun", clue: "Something seen as a warning that good or bad things are coming, like a black cat crossing your path.", alt: ["sign", "portent"] },
    { word: "intuition", pos: "noun", clue: "Knowing something from a gut feeling rather than reasoning.", alt: ["instinct", "hunch"] },
    { word: "hindsight", pos: "noun", clue: "Understanding a situation only after it's over — it's always 20/20." },
    { word: "dilemma", pos: "noun", clue: "A tough choice between two options when neither one is good.", alt: ["predicament"] },
    { word: "compromise", pos: "noun", clue: "A deal where each side gives up something so they can agree.", alt: ["middle ground"] },
    { word: "consensus", pos: "noun", clue: "When everyone in a group agrees." },
    { word: "ultimatum", pos: "noun", clue: "A final demand: do this, or else." },
    { word: "veto", pos: "noun", clue: "The power to reject a decision or block a law, like a president refusing to sign a bill." },
    { word: "filibuster", pos: "noun", clue: "Giving an extremely long speech in the Senate just to delay a vote." },
    { word: "gerrymander", pos: "verb", clue: "To redraw voting districts in odd shapes to help one party win." },
    { word: "referendum", pos: "noun", clue: "A vote where the public directly decides a single issue, like Brexit.", alt: ["ballot measure", "plebiscite"] },
    { word: "incumbent", pos: "noun", clue: "The person currently holding a political office who's running again." },
    { word: "diplomat", pos: "noun", clue: "An official who represents their country in talks with other nations.", alt: ["ambassador", "envoy"] },
    { word: "embargo", pos: "noun", clue: "An official ban on trading with another country." },
    { word: "asylum", pos: "noun", clue: "Protection a country grants to someone fleeing danger in their homeland.", alt: ["refuge", "sanctuary"] },
    { word: "perjury", pos: "noun", clue: "The crime of lying under oath." },
    { word: "plagiarism", pos: "noun", clue: "Copying someone else's work and passing it off as your own." },
    { word: "vandalism", pos: "noun", clue: "Deliberately damaging someone else's property." },
    { word: "extortion", pos: "noun", clue: "Getting money out of someone by threatening them.", alt: ["blackmail"] },
    { word: "defamation", pos: "noun", clue: "Damaging someone's reputation by spreading false claims about them.", alt: ["slander", "libel"] },
    { word: "bribe", pos: "noun", clue: "Money or gifts slipped to someone so they'll do something dishonest.", alt: ["kickback", "payoff"] },
    { word: "counterfeit", pos: "adjective", clue: "Made to look exactly like the real thing to fool people, like phony money.", alt: ["forged", "fake", "knockoff"] },
    { word: "vigilante", pos: "noun", clue: "An ordinary citizen who takes the law into their own hands, like Batman." },
    { word: "anonymous", pos: "adjective", clue: "From someone whose name isn't known or shared." },
    { word: "alias", pos: "noun", clue: "A fake name someone goes by to hide who they are.", alt: ["pseudonym", "pen name"] },
    { word: "incognito", pos: "adjective", clue: "In disguise so no one recognizes you — also a private browser tab." },
    { word: "encryption", pos: "noun", clue: "Scrambling data so only the right person can read it." },
    { word: "phishing", pos: "noun", clue: "Fake emails or texts designed to trick you into handing over your password.", alt: ["scam"] },
    { word: "malware", pos: "noun", clue: "Harmful software that sneaks onto your computer.", alt: ["virus", "spyware", "ransomware"] },
    { word: "firewall", pos: "noun", clue: "A security barrier that blocks unwanted traffic from reaching your network." },
    { word: "bandwidth", pos: "noun", clue: "How much data a connection can handle — or how much energy you have left for new tasks.", alt: ["capacity"] },
    { word: "glitch", pos: "noun", clue: "A small, sudden malfunction in a game or system.", alt: ["bug"] },
    { word: "obsolete", pos: "adjective", clue: "Out of date and no longer used, like a fax machine.", alt: ["outdated"] },
    { word: "vintage", pos: "adjective", clue: "Old but stylish and collectible, from a past era.", alt: ["retro"] },
    { word: "minimalist", pos: "noun", clue: "Someone who chooses to live with as few possessions as possible." },
    { word: "hoarder", pos: "noun", clue: "Someone who can't bring themselves to throw anything away." },
    { word: "connoisseur", pos: "noun", clue: "Someone with refined taste who can judge fine wine, art, or food.", alt: ["expert", "aficionado"] },
    { word: "amateur", pos: "noun", clue: "Someone who does something for fun, not as a paid pro.", alt: ["hobbyist"] },
    { word: "prodigy", pos: "noun", clue: "A young person with jaw-dropping talent, like a ten-year-old concert pianist.", alt: ["child genius", "wunderkind"] },
    { word: "mentor", pos: "noun", clue: "An experienced advisor who takes someone newer under their wing.", alt: ["coach"] },
    { word: "nemesis", pos: "noun", clue: "Your worst enemy — the one opponent you can never seem to beat.", alt: ["archenemy", "rival"] },
    { word: "scapegoat", pos: "noun", clue: "Someone unfairly blamed for everyone else's mistakes.", alt: ["fall guy"] },
    { word: "martyr", pos: "noun", clue: "Someone who suffers or dies for their beliefs — or who makes sure everyone knows how much they sacrifice." },
    { word: "tycoon", pos: "noun", clue: "A rich, powerful businessperson who owns a huge empire.", alt: ["mogul", "magnate", "billionaire"] },
    { word: "heir", pos: "noun", clue: "The person in line to inherit someone's fortune or throne.", alt: ["heiress", "successor"] },
    { word: "inheritance", pos: "noun", clue: "Money or property you receive when a relative dies.", alt: ["estate"] },
    { word: "eulogy", pos: "noun", clue: "A speech honoring someone at their funeral." },
    { word: "obituary", pos: "noun", clue: "A newspaper notice announcing someone's death and summing up their life." },
    { word: "epitaph", pos: "noun", clue: "The words carved on a gravestone." },
    { word: "autopsy", pos: "noun", clue: "A medical examination of a body to find the cause of death." },
    { word: "quarantine", pos: "noun", clue: "Keeping someone isolated so a disease doesn't spread.", alt: ["isolation", "lockdown"] },
    { word: "pandemic", pos: "noun", clue: "A disease outbreak that spreads across the entire world.", alt: ["epidemic"] },
    { word: "antidote", pos: "noun", clue: "A medicine that cancels out a poison." },
    { word: "adrenaline", pos: "noun", clue: "The hormone that rushes through you when you're scared or thrilled." },
    { word: "metabolism", pos: "noun", clue: "How fast your body burns through energy and food." },
    { word: "extinct", pos: "adjective", clue: "Gone forever, with none left anywhere — like the dodo." },
    { word: "evolution", pos: "noun", clue: "The slow change of living things over many generations, as Darwin described." },
    { word: "photosynthesis", pos: "noun", clue: "The process plants use to turn sunlight into food." },
    { word: "gravity", pos: "noun", clue: "The force that makes things fall to the ground." },
    { word: "erosion", pos: "noun", clue: "The slow wearing away of rock and soil by wind and water." },
    { word: "mirage", pos: "noun", clue: "An illusion of water shimmering on a hot road or in the desert." },
    { word: "constellation", pos: "noun", clue: "A group of stars that forms a picture, like Orion or the Big Dipper." },
    { word: "equator", pos: "noun", clue: "The imaginary line around the middle of the Earth." },
    { word: "archipelago", pos: "noun", clue: "A chain or cluster of islands, like Hawaii or the Philippines." },
    { word: "oasis", pos: "noun", clue: "A green spot with water in the middle of a desert." },
    { word: "labyrinth", pos: "noun", clue: "A complicated network of passages that's hard to find your way out of.", alt: ["maze"] },
    { word: "utopia", pos: "noun", clue: "An imaginary, perfect society where everything is ideal.", alt: ["paradise"] },
    { word: "dystopia", pos: "noun", clue: "A nightmarish future society, like in The Hunger Games." },
    { word: "anarchy", pos: "noun", clue: "Total disorder with no government or rules at all.", alt: ["chaos", "lawlessness"] },
    { word: "renaissance", pos: "noun", clue: "A rebirth of art and ideas — or the era of Leonardo da Vinci.", alt: ["revival"] },
    { word: "mythology", pos: "noun", clue: "The ancient stories about gods and heroes, like Zeus and Thor.", alt: ["myths", "legends"] },
    { word: "hieroglyphics", pos: "noun", clue: "The picture writing of ancient Egypt.", alt: ["hieroglyphs"] },
    { word: "anecdote", pos: "noun", clue: "A short, amusing story about something that happened to you." },
    { word: "metaphor", pos: "noun", clue: "Saying one thing IS another to compare them, like 'life is a rollercoaster.'" },
    { word: "alliteration", pos: "noun", clue: "Repeating the same starting sound, like 'Peter Piper picked a peck of pickled peppers.'" },
    { word: "onomatopoeia", pos: "noun", clue: "A word that sounds like what it describes, like 'buzz,' 'sizzle,' or 'boom.'" },
    { word: "palindrome", pos: "noun", clue: "A word that reads the same backward and forward, like 'racecar.'" },
    { word: "acronym", pos: "noun", clue: "A word made from first letters, like NASA or LOL.", alt: ["abbreviation", "initialism"] },
    { word: "hyperbole", pos: "noun", clue: "Wildly overstating things for effect, like 'I've told you a million times.'", alt: ["exaggeration"] },
    { word: "oxymoron", pos: "noun", clue: "Two opposite words side by side, like 'jumbo shrimp' or 'deafening silence.'" },
    { word: "satire", pos: "noun", clue: "Humor that mocks people or society to make a point, like The Onion.", alt: ["parody", "spoof"] },
    { word: "parody", pos: "noun", clue: "A funny imitation of a well-known song, movie, or person, like a Weird Al song.", alt: ["spoof", "satire"] },
    { word: "protagonist", pos: "noun", clue: "The lead character a story follows, like Harry Potter in his books.", alt: ["hero", "main character"] },
    { word: "monologue", pos: "noun", clue: "A long speech by one person — late-night hosts open their shows with one.", alt: ["soliloquy"] },
    { word: "improvise", pos: "verb", clue: "To make it up on the spot without any preparation.", alt: ["ad-lib", "wing it", "improv"] },
    { word: "rehearsal", pos: "noun", clue: "A run-through before the real performance, often in costume the night before.", alt: ["practice", "dress rehearsal"] },
    { word: "debut", pos: "noun", clue: "Someone's very first public appearance or performance." },
    { word: "critic", pos: "noun", clue: "A person whose job is to review and rate movies, books, or restaurants.", alt: ["reviewer"] },
    { word: "masterpiece", pos: "noun", clue: "An artist's greatest work, like the Mona Lisa." },
    { word: "burnout", pos: "noun", clue: "Total physical and mental exhaustion from too much stress at work." },
    { word: "sabbatical", pos: "noun", clue: "A long break from your job to rest, travel, or study — then you come back." },
    { word: "nomad", pos: "noun", clue: "Someone who moves from place to place with no permanent home — 'digital ___.'", alt: ["wanderer", "drifter"] },
    { word: "expat", pos: "noun", clue: "Someone who lives in a country other than the one they're from.", alt: ["expatriate", "emigrant"] },
    { word: "heirloom", pos: "noun", clue: "A treasured item passed down through generations of a family." },
    { word: "genealogy", pos: "noun", clue: "The study of your family tree and ancestors.", alt: ["ancestry"] },
    { word: "telepathy", pos: "noun", clue: "Reading minds or communicating using only your thoughts." },
    { word: "psychic", pos: "noun", clue: "A person who claims they can see the future or sense things others can't.", alt: ["clairvoyant", "medium", "fortune teller"] },
    { word: "conspiracy", pos: "noun", clue: "A secret plan by a group to do something illegal or harmful — or a wild 'theory' about one.", alt: ["plot"] },
    { word: "sustainable", pos: "adjective", clue: "Able to keep going without using up resources or harming the planet.", alt: ["eco-friendly", "green"] },
    { word: "renewable", pos: "adjective", clue: "Describes energy that won't run out, like solar or wind.", alt: ["clean"] },
    { word: "cryptocurrency", pos: "noun", clue: "Digital money like Bitcoin that isn't controlled by any bank.", alt: ["crypto"] },
    { word: "deepfake", pos: "noun", clue: "An AI-generated video that makes someone appear to say or do things they never did." },
    { word: "clickbait", pos: "noun", clue: "A misleading headline designed to lure you in — 'You won't BELIEVE what happened next!'" },
    { word: "doomscrolling", pos: "noun", clue: "Endlessly swiping through bad news on your phone when you should be asleep.", alt: ["doomscroll"] },
    { word: "catfish", pos: "verb", clue: "To pretend to be someone else online to lure a person into a relationship." },
    { word: "troll", pos: "noun", clue: "Someone who posts provocative comments online just to upset people." },
    { word: "loyalty", pos: "noun", clue: "Sticking by someone through thick and thin.", alt: ["faithfulness", "devotion"] },
    { word: "integrity", pos: "noun", clue: "Doing the right thing even when no one is watching.", alt: ["honesty", "character"] },
    { word: "charisma", pos: "noun", clue: "That magnetic personality that makes people want to follow you.", alt: ["charm", "rizz"] },
    { word: "ego", pos: "noun", clue: "Your sense of self-importance — it can get bruised or inflated." },
    { word: "jargon", pos: "noun", clue: "Special words a profession uses that outsiders don't understand, like 'synergy' in an office.", alt: ["lingo", "buzzwords"] },
    { word: "etiquette", pos: "noun", clue: "The rules of polite behavior, like which fork to use.", alt: ["manners"] },
    { word: "zeitgeist", pos: "noun", clue: "The general mood and spirit of a particular era." },
    { word: "taboo", pos: "noun", clue: "A subject or action that society considers off-limits." },
    { word: "stigma", pos: "noun", clue: "A mark of shame or disgrace attached to something, like asking for help with mental health." },
    { word: "stereotype", pos: "noun", clue: "An oversimplified idea about what a whole group of people is like." },
    { word: "prejudice", pos: "noun", clue: "Judging people unfairly before you know them.", alt: ["bias", "bigotry"] }
  ]
};
